blog/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('blogger/<int:pk>', views.BloggerDetailView.as_view(), name='blogger-detail'),
    path('<int:pk>', views.PostDetailView.as_view(), name='post-detail'),
    path('blogs/', views.PostListView.as_view(), name='post-list'),
    path('bloggers/', views.BloggerListView.as_view(), name='blogger-list'),
    path('blog/<int:pk>/comment/', views.BlogCommentCreate.as_view(), name='comment_create')
]

diyblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', RedirectView.as_view(url='blog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone

from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.


class Blogger(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(
        verbose_name="user's avatar", 
        name='avatar', 
        null=True,
        blank=True)

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('blogger-detail', args=[str(self.id)])


    @property
    def first_name(self):
        return self.user.first_name

    @property
    def last_name(self):
        return self.user.last_name


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Blogger.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.blogger.save()


class Post(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField(null=False, blank=True)
    author = models.ForeignKey(Blogger, on_delete=models.SET_NULL, null=True)
    publish = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-publish',)

    def get_absolute_url(self):
        return reverse('post-detail', args=[str(self.id)])


class Comment(models.Model):
    author = models.ForeignKey(Blogger, on_delete=models.CASCADE, null=False)
    blog = models.ForeignKey(Post, on_delete=models.CASCADE, null=False)
    text = models.TextField(null=False, blank=False)
    publish = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-publish',)
    

blog/forms.py
from django import forms

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.urls import reverse

from . import models


def index(request):
    return render(request, 'index.html', context={})


class BloggerDetailView(generic.DetailView):
    model = models.Blogger


class PostDetailView(generic.DetailView):
    model = models.Post


class PostListView(generic.ListView):
    model = models.Post
    paginate_by = 10


class BloggerListView(generic.ListView):
    model = models.Blogger
    paginate_by = 10


class BlogCommentCreate(LoginRequiredMixin, CreateView):
    model = models.Comment
    fields = ['text',]

    def get_success_url(self):
        return reverse('post-detail', kwargs={'pk': self.kwargs['pk']})

    def get_context_data(self, **kwargs):
        context = super(BlogCommentCreate, self).get_context_data(**kwargs)
        context["post"] = get_object_or_404(models.Post, pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        form.instance.author = self.request.user.blogger
        form.instance.blog = get_object_or_404(models.Post, pk=self.kwargs['pk'])

        return super(BlogCommentCreate, self).form_valid(form)

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    {% comment %} {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "css/styles.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}">
    <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script> {% endcomment %}
    
    <div id="title">
        {% block title %}
            <title>Blog</title>
        {% endblock %}
    </div>
    
</head>

<body>

    <div class="row">

        <div class="col-sm-2">
            {% block sidebar %}
                <ul class="sidebar-nav">
                    <li><a href="{% url 'index' %}">Home</a></li>
                    <li><a href="{% url 'post-list' %}">All blogs</a></li>
                    <li><a href="{% url 'blogger-list' %}">All bloggers</a></li>
                </ul>

                <ul class="sidebar-nav">
                    {% if user.is_authenticated %}
                        <a href="{{ user.blogger.get_absolute_url }}"> {{ user.get_username }}</a>
                        <a href="{% url 'logout' %}?next={{ request.path }}">Logout</a>
                    {% else %}
                        <a href="{% url 'login' %}?next={{ request.path }}">Login</a>
                    {% endif %}
                </ul>
            {% endblock %}
        </div>

        <div class="col-sm-10">
            {% block content %} {% endblock %}

            {% block pagination %}
                {% if is_paginated %}
                    <div class="pagination">
                        <span class="page-links">
                            {% if page_obj.has_previous %}
                                <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">prev</a>
                            {% endif %}
                            <span class="page-current">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </span>
                            {% if page_obj.has_next %}
                                <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                            {% endif %}
                        </span>
                    </div>
                {% endif %}
            {% endblock %}    
        </div>
    
    </div>

</body>

</html>

blog/templates/blog/blogger_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">

    <div class="row">
    
        <div class="col-2">
            <img src="{{ blogger.avatar }}" alt="Avatar">
            <p>{{ blogger }}</p>
        </div>

        <div class="col-8">
            <p>{{blogger.user.first_name}} {{blogger.user.last_name}}</p>

        </div>

    </div>

    <div class="row">
    <ul>
        <h1>Blogs list</h1>
        {% if blogger.post_set.all %}
            {% for post in blogger.post_set.all %}
                <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a> ({{ post.publish }})</li>
            {% endfor %}
        {% else %}
            <p>There are no blogs</p>
        {% endif %}       
    </ul>
    
    </div>

</div>
{% endblock %}

blog/templates/blog/blogger_list.html
{% extends 'base.html' %}

{% block content %}

    <h1 class="list_title">All blogger</h1>

    {% if blogger_list %}
        <ul>
            {% for blogger in blogger_list %}
                <li>
                    <a href="{{ blogger.get_absolute_url }}">{{blogger}}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no blogers</p>
    {% endif %}

{% endblock %}

blog/templates/blog/comment_form.html
{% extends 'base.html' %}

{% block content %}

    <p>New comment for post <a href="{% url 'post-detail' post.pk %}">{{ post.title }}</a> by <a href="{% url 'blogger-detail' post.author.pk %}">{{ post.author }}</a></p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid">

    <div class="row">
    
        <div class="col-2">
            <img src="{{ post.author.avatar }}" alt="Avatar">
            <p><a href="{{ post.author.get_absolute_url }}">{{ post.author }}</a></p>
        </div>

        <div class="col-8">
            <h1><a href="{{ post.get_absolute_url }}">{{ post }}</a></h1>
            <h4>{{ post.publish }}</h4>

            <p class="post__text">{{ post.text }}</p>
        </div>

    </div>

    <div class="row">
        <h1 class="comments">Comments</h1>
    </div>

    <div class="row">
        <div class="comments">
            {% for comment in post.comment_set.all %}
                <p>
                    <a href="{{ comment.author.get_absolute_url }}">{{ comment.author }}</a> ({{ comment.publish }}) - {{ comment.text }}
                </p>
            {% endfor %}

            {% if user.is_authenticated %}
                <a href="{% url 'comment_create' post.id %}">Add a new comment</a>
            {% else %}
                <p><a href="{% url 'login' %}?next={{ request.path }}">Login</a> to add a new comment</p>
            {% endif %}
        
        </div>
    </div>

</div>

{% endblock  %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}

{% block content %}

    <h1 class="list_title">All blogs</h1>

    {% if post_list %}
        <ul>
            {% for post in post_list %}
                <li>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a> ({{ post.publish }}) - 
                    <a href="{{ post.author.get_absolute_url }}">{{ post.author }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no posts</p>    
    {% endif %}

{% endblock %}

blog/templates/index.html
{% extends "base.html" %}

{% block content %}

    <h1>Blog Home</h1>

    <p class="main_content">Welcome to my Blog site</p>

    <p>This is diy django mini blog task from developer.mozilla.org</p>
    
{% endblock %}